# Build settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "Audrey Watters"
description: > # this means to ignore newlines until "email:"
   Writer

url: http://audreywatters.com

email: mail@audreywatters.com
#blog logo
logo: "/assets/images/new_hack_logo.jpg"
logo2: "/assets/images/hack.png"
# blog cover
cover: "/assets/images/typewriter.png"
covercredits: "http://bryanmmathers.com/"

name: 'Audrey Watters'
author: 'Audrey Watters'
author_image: "/assets/images/author.jpg"

paginate:	10
paginate_path: "/blog/page:num"
permalink: /:categories/:year/:month/:day/:title 

url: "http://audreywatters.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@audreywatters'

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	
#    desc: 
#    share_url: 
#    share_title: 
#    share_link: 

# - icon:	facebook
#   url:	https://facebook.com/audreywatters
#    desc: Friend me on Facebook
#    share_url: http://www.facebook.com/sharer/sharer.php
#    share_title: ?title=
#    share_link: "?u="

#  - icon:	github
#    url:	https://github.com/audreywatters/audreywatters.com
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	
#    desc:	
#    share_url:
#    share_title:
#    share_link:

#  - icon: rss
#    url:  http://audreywatters.com/feed.xml
#    desc: Subscribe
#    share_url:
#    share_title:
#    share_link:

  - icon: envelope
    url:  mailto:mail@audreywatters.com
    desc: Email
    share_url:
    share_title:
    share_link:    
  
